    file_path: '/gpfs/data/fs71707/mwielsch1/SA_EPI/nxt_max/docker_test/'
    file_name: '*.R{1,2}.fastq.gz'
    trim_adapter: '/gpfs/data/fs71707/mwielsch1/SA_EPI/nxt_max/REF/NexteraPE-PE.fa'
    homo_sapiens_ref: '/gpfs/data/fs71707/mwielsch1/SA_EPI/nxt_max/REF/GRCh38/Homo_sapiens_GRCh38'
    quast_ref: '/gpfs/data/fs71707/mwielsch1/SA_EPI/nxt_max/REF/quast_ref/'

    checkm_db: '/gpfs/data/fs71707/mwielsch1/SA_EPI/nxt_max/REF/checkm'
    saureus_ref: '/gpfs/data/fs71707/mwielsch1/SA_EPI/nxt_max/REF/S_aureus_NCTC8325.fna'
    genomad_db: '/gpfs/data/fs71707/mwielsch1/SA_EPI/nxt_max/REF/genomad_db'
    checkv_db: '/gpfs/data/fs71707/mwielsch1/SA_EPI/nxt_max/REF/checkv-db-v1.3'
    pharokka_db: '/gpfs/data/fs71707/mwielsch1/SA_EPI/nxt_max/REF/pharokka_db'
